---
output:
  md_document:
    variant: markdown_github
bibliography: ../bibliography_V2.bib
---

# Section 3. Data transfer and data integrity
## `Examples of existing data transfer & data integrity checks`
|**Repository or tool source** | **Data transfer integrity checks in place** |
|------------|------------------------|
| ENA | MD5sum available for "most" downloads. Submission tool generates this, otherwise user needs to upload [@ena_common_run_errors] ncbi  |
| NCBI GEO | MD5 "recommended" for submissions [@geo_submission_guide] |
| NCBI SRA |  MD5 is a parameter during submission (as of the 2010 guide [@sra_quick_start_guide]) There is a ‘vdb-validate’ tool for checking download integrity [@sra_tools] |
| MGnify | "Intermediate checksums" in 2020 paper [@mitchell2020mgnify] |
| MG RAST | "Data hygiene" (Preprocessing, dereplication, DRISEE, screening) [@meyer2008metagenomics] |

|Comments/questions: |
|--------------------|
| |

## `Data integrity considerations by file type`
|**File type**| **Integrity check** | **Other considerations for quality and transferability** |
|------------|-------------------------|------------|
| FASTQ | Read count, checksum (MD5sum, SEGUID [@bassi2007biopython] [@babnigg2006database], etc.) | Determination of +33/+64 format from compressed files |
| FASTA | Read count, checksum (MD5sum, SEGUID [@bassi2007biopython] [@babnigg2006database], etc.) | |
| .faa | SEGUID [@bassi2007biopython] [@babnigg2006database] | Annotation pipeline, assembly quality |
| GFF/GTF | | Annotation pipeline, assembly quality |

|Comments/questions: |
|--------------------|
| |

# References