---
output:
  md_document:
    variant: markdown_github
bibliography: ../bibliography_V2.bib
---

## 2.8 Metabolomics

A searchable and exportable tab-separated [table](Metabolome_Technical_Metadata.tsv) of the following metadata is now available.

## Minimal technical metadata for metabolomics
|**metadata**| **definition/examples** | **adapted from source** |
|------------|-------------------------|------------|
| Project title | Name of the project |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Project description | Overall description of the project |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Contact information | Person(s) responsible for contact including their affiliation |**MetaboLights** [@metabolights],  **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Sample species | Species of the sample |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Sample type | Whether the sample was experimental/blank/control/qc |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote] |
| Instrument | Description of instrument used including manufacturer & mode |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| File type | Type of file uploaded (e.g. RAW, SEARCH, RESULT, etc.) |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|

|Comments/questions: |
|--------------------|
| |

## &emsp; Minimal technical metadata for metabolomics - experimental protocol edition
|**metadata**| **definition/examples** | **adapted from source** |
|------------|-------------------------|------------|
| Sample collection protocol | Description of sampling procedure, origin of sample, time point of collection, storage, etc. |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Extraction protocol | Protocol of extraction steps before analysis including control samples |**MetaboLights** [@metabolights], **Metabolomics Workbench** [@sud2016metabolomics], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Chromatography protocol | Description of instrument and column, mobile phase and gradient as well a settings used |**MetaboLights** [@metabolights], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Mass spectrometry protocol | Description of instrument, ion source, ionisation mode, mz range and settings |**MetaboLights** [@metabolights], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Data transformation protocol | Details of pipelines, methods and software used to transform the raw data |**MetaboLights** [@metabolights], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|
| Metabolite identification protocol | Details of methods, pipelines, reference databases, and software used to identify and annotate |**MetaboLights** [@metabolights], **Metabolonote** [@ara2015metabolonote], **MSI** [@fiehn2007metabolomics]|

|Comments/questions: |
|--------------------|
| |

We also highly encourage the readers of this GitHub to look for examples of submitted metabolomic samples and analyses in **MetabolomeXchange** [@metabolomexchange] that holds datasets from **MetagoLights, Metabolic Repository Bordeaux, Metabolomics Workbench and Metabolonote**. Publications **MetaboLights: a resource evolving in response to the needs of its scientific community** [@metabolights], **Metabolonote: a wiki-based database for managing hierarchical metadata of metabolome analyses** [@ara2015metabolonote], **Metabolomics Workbench: An international repository for metabolomics data and metadata, metabolite standards, protocols, tutorials and training, and analysis tools** [@sud2016metabolomics] and **The metabolomics standards initiative (MSI)** [@fiehn2007metabolomics] in the 'adapted from source' section can be found online.

# References